import utils
import ast
from tqdm import trange
from pandasgui import show

# Lecture des donnees

# lit le fichier brut
# data = utils.read_data("data/2025.json")
# sol = utils.read_data("data/exercises.json")

# transforme les donnees AlgoPython en DataFrame exploitable
# df = utils.AlgoPython_data(data)

# Tests

# analyse detaillee d'un user
# utils.analyse_user(46272, df)

# comparaison manuelle entre deux programmes si besoin
# p1 = utils.code_to_ast(df.iloc[0]["code"])
# p2 = utils.code_to_ast(df.iloc[1]["code"])
# print(utils.ast_dump(p1))
# print(utils.primary_code_error_two_prog(p1, p2))

# affichage du DataFrame si besoin
# show(df[df["code"] != ""])

# Echantillonnage
# c = utils.cas1(df, sol)
c = utils.read_data("data/cas1.json")
# show(c)

utils.cas2(c)

all_primary = {'MISSING_CALL_STATEMENT', 'UNNECESSARY_FUNCTION', 'UNNECESSARY_VARIABLE', 'MISSING_FUNCTION_DEFINITION', 'UNNECESSARY_CONDITIONAL', 'MISSING_CONST_VALUE', 'UNNECESSARY_FOR_LOOP', 'MISSING_ASSIGN_STATEMENT', 'INCORRECT_STATEMENT_POSITION_FOR', 'MISSING_FOR_LOOP', 'INCORRECT_OPERATION_IN_ASSIGN', 'MISSING_VARIABLE', 'UNNECESSARY_ARGUMENT', 'UNNECESSARY_CONST_VALUE', 'MISSING_IF_STATEMENT', 'MISSING_OPERATION', 'NODE_TYPE_MISMATCH', 'UNNECESSARY_CALL_STATEMENT', 'VARIABLE_MISMATCH', 'UNNECESSARY_OPERATION', 'INCORRECT_STATEMENT_POSITION_CALL', 'INCORRECT_STATEMENT_POSITION_IF', 'UNNECESSARY_VAR', 'CONST_VALUE_MISMATCH', 'UNNECESSARY_ASSIGN_STATEMENT', 'INCORRECT_STATEMENT_POSITION_FUNCTION'}
all_typo = {'F_CALL_AVANCER_ERROR', 'F_CALL_UNNECESSARY_ARC', 'F_CALL_INCORRECT_POSITION_BAS', 'F_CALL_MISSING_AVANCER', 'F_CALL_UNNECESSARY_DROITE', 'F_CALL_UNNECESSARY_GAUCHE', 'F_CALL_INCORRECT_POSITION_GAUCHE', 'EXP_ERROR_OPERATOR', 'F_CALL_MISSING_TOURNER', 'F_CALL_MISSING', 'F_CALL_MISSING_BAS', 'EXP_ERROR_ASSIGNMENT_UNNECESSARY', 'F_CALL_MISSING_LEVER', 'F_CALL_MISSING_COULEUR', 'F_CALL_INCORRECT_POSITION_AVANCER', 'CS_MISSING', 'F_CALL_MISSING_ARC', 'F_CALL_INCORRECT_POSITION_PRINT', 'F_CALL_MISSING_DROITE', 'F_CALL_MISSING_POSER', 'EXP_ERROR_OPERATION', 'F_CALL_MISSING_HAUT', 'F_CALL_INCORRECT_POSITION_COULEUR', 'EXP_ERROR_OPERANDS', 'F_CALL_INCORRECT_POSITION_DROITE', 'LO_FOR_MISSING', 'LO_BODY_MISPLACED', 'F_CALL_UNNECESSARY_HAUT', 'F_CALL_GAUCHE_ERROR', 'F_CALL_MISSING_GAUCHE', 'F_CALL_INCORRECT_POSITION_POSER', 'F_CALL_UNNECESSARY_PRINT', 'F_CALL_PRINT_ERROR_ARG', 'F_CALL_ARC_ERROR', 'F_CALL_UNNECESSARY_BAS', 'F_CALL_INCORRECT_POSITION_LEVER', 'F_CALL_INCORRECT_POSITION_ARC', 'EXP_ERROR_ASSIGNMENT_MISSING', 'F_CALL_UNNECESSARY_TOURNER', 'F_CALL_INCORRECT_POSITION_TOURNER', 'F_CALL_COULEUR_ERROR', 'LO_FOR_UNNECESSARY', 'LO_BODY_MISSING_NOT_PRESENT_ANYWHERE', 'F_CALL_UNNECESSARY', 'F_CALL_DROITE_ERROR', 'F_CALL_UNNECESSARY_AVANCER', 'F_CALL_TOURNER_ERROR', 'F_CALL_UNNECESSARY_COULEUR', 'F_CALL_BAS_ERROR', 'F_CALL_UNNECESSARY_POSER', 'LO_FOR_MISPLACED', 'LO_FOR_NUMBER_ITERATION_ERROR', 'F_DEFINITION_UNNECESSARY', 'LO_FOR_NUMBER_ITERATION_ERROR_UNDER2', 'F_CALL_HAUT_ERROR', 'F_DEFINITION_MISSING', 'F_CALL_UNNECESSARY_LEVER', 'F_CALL_INCORRECT_POSITION_HAUT', 'F_CALL_MISSING_PRINT', 'LO_BODY_ERROR'}

# filtre_primary = set()
# for i in {'NODE_TYPE_MISMATCH', 'INCORRECT_STATEMENT_POSITION_IF', 'UNNECESSARY_FUNCTION', 'UNNECESSARY_CALL_STATEMENT', 'UNNECESSARY_ASSIGN_STATEMENT', 'UNNECESSARY_FOR_LOOP', 'UNNECESSARY_ARGUMENT', 'CONST_VALUE_MISMATCH', 'UNNECESSARY_CONST_VALUE', 'VARIABLE_MISMATCH', 'INCORRECT_OPERATION_IN_ASSIGN', 'UNNECESSARY_OPERATION', 'UNNECESSARY_VARIABLE', 'INCORRECT_STATEMENT_POSITION_FOR', 'INCORRECT_STATEMENT_POSITION_CALL', 'INCORRECT_STATEMENT_POSITION_FUNCTION', 'UNNECESSARY_VAR', 'UNNECESSARY_CONDITIONAL'}:
#     if i.startswith("MISSING"):
#         print(i, end=" ")
#     else:
#         filtre_primary.add(i)
# print()
# print(filtre_primary)